export type RetirementStrategy = 'debitFree' | 'age' | 'percentRule' | 'targetSavings';
export type GrowthStrategy = 'fixed' | 'percentage_increase';
export type IncomeTaxStrategy = 'simple' | 'ordinaryIncome' | 'capitalGains' | 'taxExempt' | 'qualifiedDividends' | 'selfEmploymentTax';
export type InflationGrowthStrategy = 'fixed' | 'percentage_increase';
export type ExpensesGrowthStrategy = 'fixed' | 'percentage_increase';
export type IraContributionStrategy = 'fixed' | 'percent_of_income' | 'max';
export type InvestmentGrowthApplicationStrategy = 'start' | 'end';
export type TaxableContributionStrategy = 'fixed' | 'percent_of_income';
export type DebtPaymentStrategy = 'fixed' | 'max' | 'percentage_of_debt'
export type AllowNegativeDisposableIncome = 'none' | 'minimum_only' | 'full';